# Generated by Django 2.2.12 on 2020-04-11 11:38

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', error_messages={'blank': 'Name of the fruit should be provided.', 'unique': 'Already exists. The name of the fruit should be unique.'}, help_text='Name of the Fruit.', max_length=30, unique=True, verbose_name='Fruit Name')),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, error_messages={'blank': 'Price of the fruit should be provided.'}, help_text='Price of the Fruit.', max_digits=5, validators=[website.models.NegativeNumebrValidator], verbose_name='Fruit Price')),
                ('Color', models.CharField(default='', error_messages={'blank': 'Color of the fruit should be provided.'}, help_text='Color of the Fruit.', max_length=30, verbose_name='Fruit Color')),
            ],
        ),
    ]
