# Generated by Django 2.2.12 on 2020-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200411_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='Name',
            field=models.CharField(default='', error_messages={'blank': 'Name of the fruit should be provided.'}, help_text='Name of the Fruit.', max_length=30, verbose_name='Fruit Name'),
        ),
    ]
