# Generated by Django 2.2.12 on 2020-04-12 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20200411_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', error_messages={'blank': 'Query should be provided.'}, help_text='MySQL Query', max_length=300, verbose_name='MySQL Query')),
                ('stamp', models.DateTimeField(auto_now_add=True, verbose_name='Query Created Date and Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
