# Generated by Django 2.2.12 on 2020-04-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_queryresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryresult',
            options={'ordering': ['-stamp'], 'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
    ]
