# Generated by Django 2.2.12 on 2020-04-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200412_1715'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fruit',
            table='fruit',
        ),
    ]
