# Generated by Django 2.2.12 on 2020-04-20 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_auto_20200412_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[(1, 'YELLOW'), (2, 'RED'), (3, 'ORANGE'), (4, 'BLUE'), (5, 'PURPLE'), (6, 'GREEN'), (7, 'BROWN'), (8, 'MAGENTA')], default=1, max_length=10, verbose_name='Color')),
                ('range', models.CharField(default='', max_length=20, verbose_name='Results Range')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='configurationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', error_messages={'blank': 'Header Name is required.'}, help_text='Header Name ( or Category) Unique Header or category name where group of                                         same stats will be displayed Linux Fruit Details DB Fruit Details Daily                                         Max Price Stats Etc…', max_length=50, verbose_name='Header Name ( or Category)')),
                ('name', models.CharField(default='', error_messages={'blank': 'Stats rules name is required'}, help_text='Stats rules name', max_length=20, verbose_name='Name')),
                ('source', models.CharField(choices=[(1, 'DATABASE'), (2, 'LINUX BOX')], default=1, error_messages={'blank': 'Source is required', 'invalid': 'Invalid source choice'}, help_text='Select source from which results are to be fetched', max_length=10, verbose_name='Source')),
                ('source_query', models.CharField(default='', error_messages={'blank': 'SQL Query/Linux Shell Command is required'}, help_text='SQL Query or Linux shell command', max_length=100, verbose_name='SQL Query/Linux Shell Command')),
                ('resultDataType', models.CharField(choices=[(1, 'INTEGER'), (2, 'FLOAT'), (3, 'STRING/TEXT'), (4, 'PYTHON LIST OR DICTIONARY')], default=4, error_messages={'blank': 'Results Data Type  is requiured'}, help_text='Results Data Type', max_length=10, verbose_name='Result Data Type')),
                ('Schedule_Run_Config', models.CharField(blank=True, default='', max_length=100, verbose_name='Schedule Run Config')),
                ('emailID', models.EmailField(blank=True, default='', help_text='Email id if incase scheduled run results need to be sent', max_length=30, verbose_name='Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.ManyToManyField(to='website.ColorRange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
