# Generated by Django 2.2.12 on 2020-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_colorrange_configurationrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorrange',
            name='color',
            field=models.CharField(choices=[('1', 'YELLOW'), ('2', 'RED'), ('3', 'ORANGE'), ('4', 'BLUE'), ('5', 'PURPLE'), ('6', 'GREEN'), ('7', 'BROWN'), ('8', 'MAGENTA')], default=1, max_length=10, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='configurationrules',
            name='resultDataType',
            field=models.CharField(choices=[('1', 'INTEGER'), ('2', 'FLOAT'), ('3', 'STRING/TEXT'), ('4', 'PYTHON LIST OR DICTIONARY')], default=4, error_messages={'blank': 'Results Data Type  is requiured'}, help_text='Results Data Type', max_length=10, verbose_name='Result Data Type'),
        ),
        migrations.AlterField(
            model_name='configurationrules',
            name='source',
            field=models.CharField(choices=[('1', 'DATABASE'), ('2', 'LINUX BOX')], default=1, error_messages={'blank': 'Source is required', 'invalid': 'Invalid source choice'}, help_text='Select source from which results are to be fetched', max_length=10, verbose_name='Source'),
        ),
    ]
