# Generated by Django 2.2.12 on 2020-04-20 15:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20200420_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='configResultsDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=100, verbose_name='Header')),
                ('statsName', models.CharField(default='', max_length=100, verbose_name='Stats Rule Name')),
                ('query_store_overall', models.CharField(default='', max_length=100, verbose_name='Whole Result Query')),
                ('query_store_DB_1', models.CharField(default='', max_length=100, verbose_name='Query for DB 1')),
                ('results_store_DB_1', models.CharField(default='', max_length=100, verbose_name='Results for DB 1')),
                ('results_store_DB_1_timestamp', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 15, 43, 59, 460371, tzinfo=utc), verbose_name='Timestamp for DB 1')),
                ('query_store_DB_2', models.CharField(default='', max_length=100, verbose_name='Query for DB 2')),
                ('results_store_DB_2', models.CharField(default='', max_length=100, verbose_name='Results for DB 2')),
                ('results_store_DB_2_timestamp', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 15, 43, 59, 460371, tzinfo=utc), verbose_name='Timestamp for DB 2')),
                ('updated_timtstamp', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 15, 43, 59, 460371, tzinfo=utc), verbose_name='Results Updated Time')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('configRules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.configurationRules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
