# Generated by Django 2.2.12 on 2020-04-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200420_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configresultsdatabase',
            name='header',
        ),
        migrations.RemoveField(
            model_name='configresultsdatabase',
            name='query_store_overall',
        ),
        migrations.RemoveField(
            model_name='configresultsdatabase',
            name='statsName',
        ),
    ]
